var GAME_LEVELS = [
  ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "x                                                         | |                  x",
   "x @                                                                            x",
   "x                                                         |o|                  x",
   "x                                                                    o o o o o x",
   "x                                                         |o|                  x",
   "x                                              o                     o o o o o x",
   "xxxx                                                      |o|                  x",
   "x  xxx                               o                        yyyyy  o o o o o x",
   "x    xxxx                                                                      x",
   "x                                                  yyyyy                       x",
   "x                                                                              x",
   "x                                       yyyyy                                  x",
   "x          yyyyy yyyyy                                                         x",
   "x                              xxxx                                            x",
   "x              do              x                                               x",
   "x o             x          o   x                                               x",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                               x",
   "x                                                                              x",
   "x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x    g     x",
   "x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x          x",
   "x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x          x",
   "x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x          x",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx          x",
   "                                                                    x          x",
   "                                                                    x          x",
   "                                                                    x          x",
   "                                                                    x          x",
   "                                                                    x          x",
   "                                                                    x          x",
   "                                                                    x          x",
   "                                                                    x          x",
   "                                                                    x          x",
   "                                                                    x          x",
   "                                                                    x          x",
   "                                                                    x          x",
   "                                                                    x          x",
   "                                                                    x          x",
   "                                                                    x          x",
   "                                                                    x          x",
   "                                                                    x          x",
   "                                                                    x          x",
   "                                                                    x          x",
   "                                                                    x          x",
   "                                                                    x          x",
   "                                                                    x          x",
   "                                                                    x          x",
   "                                                                    x          x",
   "                                                                    x          x",
   "                                                                    x          x",
   "                                                                    x          x",
   "                                                                    x          x",
   "                                                                    x          x",
   "                                                                    x          x",
   "                                                                    x          x",
   "                                                                    x          x",
   "                                                                    x          x"],
  ["x          xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "x    @                                                                     o o                                   x",
   "x                     o    o        o   o                                  o o                                   x",
   "x    o                                                                    yyyyy                                  x",
   "x                                                                                                yyyy            x",
   "x    o                              o   o                 yyyyy                                                  x",
   "x                                                                       y = = =  y =         =        =        = x",
   "x    o            s                                    o o odo o o                                               x",
   "x                                                                                         yyyy                   x",
   "x    o          yyyyy        yyyyy = = = = yyyyy       yyyyyyyyyyy     yyyyyyyyyyyy                       o o o  x",
   "x                                                                                                                x",
   "x                    | |  | |       | | |        | | |              |                                     o o o  x",
   "xxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x         x",
   "x         xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  o o o  x",
   "x                 o o                                                                        o                   x",
   "x o o o o                                         o o o o o o o         o o o o o o o                     o o o  x",
   "x                      o o                                                                   o                   x",
   "x o o o o                      o o                                                                               x",
   "x                                                        d                      d            yyyyy               x",
   "x o o o o   yyyyy  |                                                                                             x",
   "x                  | yy                                                                           |  |           x",
   "x                  |    |   yy                    o o o o o o o         o o o o o o o             |  |           x",
   "x                  |    |       |                                                                 |  |           x",
   "x                  |    |       |     yy          yyyyyyyyyyyyy=|=|=|=|=yyyyyyyyyyyyy             |  |           x",
   "x    g    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxx",
   "x         xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "x         x                                                                                                      x",
   "x         x                                                                                                      x",
   "x         x                                                                                                      x",
   "x         x                                                                                                      x",
   "x         x                                                                                                      x",
   "x         x                                                                                                      x",
   "x         x                                                                                                      x",
   "x         x                                                                                                      x",
   "x         x                                                                                                      x",
   "x         x                                                                                                      x",
   "x         x                                                                                                      x",
   "x         x                                                                                                      x",
   "x         x                                                                                                      x",
   "x         x                                                                                                      x",
   "x         x                                                                                                      x",
   "x         x                                                                                                      x",
   "x         x                                                                                                      x",
   "x         x                                                                                                      x",
   "x         x                                                                                                      x",
   "x         x                                                                                                      x",
   "x         x                                                                                                      x",
   "x         x                                                                                                      x",
   "x         x                                                                                                      x",
   "x         x                                                                                                      x",
   "x         x                                                                                                      x",
   "x         x                                                                                                      x"],
   
  ["x          xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "x     @                               oooooooooooooooooooooooooooo                                           x",
   "x oooooooooooooooooo                 x =    =     =      =      = x                                          x",
   "x oooooooooooooooooo                                                                                         x",
   "x oooooooooooooooooo                                                                                         x",
   "x oooooooooooooooooo                                                                                         x",
   "x oooooooooooooooooo                               d                                                         x",
   "x oooooooooooooooooo                                                                                         x",
   "x oooooooooooooooooo                 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                          x",
   "x oooooooooooooooooo  yyyyy          x!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                                          x",
   "x oooooooooooooooooo                 x!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                                          x",
   "x oooooooooooooooooo   d             x!!!!!!!!!!!!!!!!!!!!!!!!!!!!x       ooooooooooooooooooooooooooooo      x",
   "x oooooooooooooooooo                 x!!!!!!!!!!!!!!!!!!!!!!!!!!!!x       ooooooooooooooooooooooooooooo      x",
   "x oooooooooooooooooo              xxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!x       ooooooooooooooooooooooooooooo      x",
   "x oooooooooooooooooo                 x!!!!!!!!!!!!!!!!!!!!!!!!!!!!x       oooooggggggggggggggggggoooooo      x",
   "x oooooooooooooooooo                 x!!!!!!!!!!!!!!!!!!!!!!!!!!!!x       oooooggggggggggggggggggoooooo      x",
   "x oooooooooooooooooo                 x!!!!!!!!!!!!!!!!!!!!!!!!!!!!x       oooooggggggggggggggggggoooooo      x",
   "x oooooooooooooooooo                 x!!!!!!!!!!!!!!!!!!!!!!!!!!!!x       oooooggggggggggggggggggoooooo      x",
   "x oooooooooooooooooo  yyyyy          x!!!!!!!!!!!!!!!!!!!!!!!!!!!!x       oooooggggggggggggggggggoooooo      x",
   "x oooooooooooooooooo                 x!!!!!!!!!!!!!!!!!!!!!!!!!!!!x       oooooggggggggggggggggggoooooo      x",
   "x oooooooooooooooooo                 x!!!!!!!!!!!!!!!!!!!!!!!!!!!!x       oooooggggggggggggggggggoooooo      x",
   "x oooooooooooooooooo              xxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!x       oooooggggggggggggggggggoooooo      x",
   "x oooooooooooooooooo                 x!!!!!!!!!!!!!!!!!!!!!!!!!!!!x       ooooooooooooooooooooooooooooo      x",
   "x oooooooooooooooooo  d              x!!!!!!!!!!!!!!!!!!!!!!!!!!!!xggggggggggggggggggggggggggggggggggggggggggx",
   "x oooooooooooooooooo                 x!!!!!!!!!!!!!!!!!!!!!!!!!!!!x       ooooooooooooooooooooooooooooo      x",
   "x oooooooooooooooooo  yyyyy          x!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                                          x",
   "x oooooooooooooooooo                 x!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                                          x",
   "x oooooooooooooooooo                 x!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                                          x",
   "x oooooooooooooooooo                 x!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                                          x",
   "x oooooooooooooooooo                 x!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                                          x",
   "x oooooooooooooooooo                 x!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                                          x",
   "x oooooooooooooooooo              xxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                                          x",
   "x oooooooooooooooooo                 x!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                                          x",
   "x oooooooooooooooooo     ===         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                                          x",
   "x                                    x!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                                          x",
   "x                         yyyyyy     x!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                                          x",
   "x                                    x!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                                          x",
   "x                                    x!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                                          x",
   "x  s  s  s  s  s  s                  x!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                                          x",
   "x                                    x!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                                          x",
   "x yyyyyyyyyyyyyyyyyy                 x!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                                          x",
   "x                                    x!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                                          x",
   "x  |  |  |  |  |  |        |  |    ||x!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                                          x",
   "x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                                          x",
   "x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                                          x",
   "x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                                          x",
   "x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                                          x",
   "x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                                          x",
   "x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                                          x",
   "x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                                          x",
   "x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                                          x",
   "x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                                          x",
   "x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                                          x",
   "x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                                          x",
   "x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                                          x",
   "x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                                          x",
   "x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                                          x",
   "x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                                          x",
   "x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                                          x",
   "x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                                          x",
   "x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                                          x",
   "x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                                          x",
   "x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                                          x",
   "x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                                          x",
   "x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                                          x",
   "x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                                          x",
   "x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                                          x",
   "x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                                          x",
   "x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                                          x",
   "x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                                          x",
   "x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                                          x",
   "x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                                          x",
   "x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                                          x",
   "x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                                          x",
   "x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                                          x",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                          x",
   "                                                                                                              ",
   "                                                                                                              "],
  ["x!!!x             x",
   "x!!!x     @       x",
   "x!!!xsssssssssssssx",
   "x!!!x             x",
   "x!!!x             x",
   "x!!!x             x",
   "x!!!x             x",
   "x!!!x             x",
   "x!!!x             x",
   "x!!!x             x",
   "x!!!x             x",
   "x!!!x             x",
   "x!!!x             x",
   "x!!!x             x",
   "x!!!x             x",
   "x!!!x             x",
   "x!!!x             x",
   "x!!!x             x",
   "x!!!x             x",
   "x!!!x             x",
   "x!!!x             x",
   "x!!!x             x",
   "x!!!x             x",
   "x!!!x             x",
   "x!!!x             x",
   "x!!!x             x",
   "x!!!x             x",
   "x!!!x             x",
   "x                 x",
   "x      o    o     x",
   "x       o  o      x",
   "x        o        x",
   "x        o        x",
   "x        o        x",
   "x                 x",
   "x        o        x",
   "x       o  o      x",
   "x      o    o     x",
   "x       o  o      x",
   "x        o        x",
   "x                 x",
   "x      o   o      x",
   "x      o   o      x",
   "x      o   o      x",
   "x      o   o      x",
   "x      ooooo      x",
   "x                 x",
   "x                 x",
   "x                 x",
   "x      o   o      x",
   "x      o   o      x",
   "x      o o o      x",
   "x      o o o      x",
   "x      ooooo      x",
   "x                 x",
   "x      ooooo      x",
   "x        o        x",
   "x        o        x",
   "x        o        x",
   "x        o        x",
   "x      ooooo      x",
   "x                 x",
   "x      o    o     x",
   "x      o o  o     x",
   "x      o  o o     x",
   "x      o   oo     x",
   "x      o    o     x",
   "x                 x",
   "x                 x",
   "x                 x",
   "x                 x",
   "x                 x",
   "x                 x",
   "x                 x",
   "x                 x",
   "x                 x",
   "x                 x",
   "x                 x",
   "xgggggggggggggggggx",
   "                   "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
