var GAME_LEVELS = [
  ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "x                                                         | |                  x",
   "x @                                                                            x",
   "x                                                         |o|                  x",
   "x                                                                    o o o o o x",
   "x                                                         |o|                  x",
   "x                                              o                     o o o o o x",
   "xxxx                                                      |o|                  x",
   "x  xxx                               o                        yyyyy  o o o o o x",
   "x    xxxx                                                                      x",
   "x                                                  yyyyy                       x",
   "x                                                                              x",
   "x                                       yyyyy                                  x",
   "x          yyyyy yyyyy                                                         x",
   "x                              xxxx                                            x",
   "x              do              x                                               x",
   "x o             x          o   x                                               x",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                               x",
   "x                                                                              x",
   "x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x    g     x",
   "x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x          x",
   "x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x          x",
   "x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x          x",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx          x",
   "                                                                    x          x",
   "                                                                    x          x",
   "                                                                    x          x",
   "                                                                    x          x",
   "                                                                    x          x",
   "                                                                    x          x",
   "                                                                    x          x",
   "                                                                    x          x",
   "                                                                    x          x",
   "                                                                    x          x",
   "                                                                    x          x",
   "                                                                    x          x",
   "                                                                    x          x",
   "                                                                    x          x",
   "                                                                    x          x",
   "                                                                    x          x",
   "                                                                    x          x",
   "                                                                    x          x",
   "                                                                    x          x",
   "                                                                    x          x",
   "                                                                    x          x",
   "                                                                    x          x",
   "                                                                    x          x",
   "                                                                    x          x",
   "                                                                    x          x",
   "                                                                    x          x",
   "                                                                    x          x",
   "                                                                    x          x",
   "                                                                    x          x",
   "                                                                    x          x",
   "                                                                    x          x",
   "                                                                    x          x",
   "                                                                    x          x"],
  ["x          xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "x    @                                                                     o o                                   x",
   "x                     o    o        o   o                                  o o                                   x",
   "x    o                                                                    yyyyy                                  x",
   "x                                                                                                yyyy            x",
   "x    o                              o   o                 yyyyy                                                  x",
   "x                                                                       y = = =  y =         =        =        = x",
   "x    o            s                                    o o odo o o                                               x",
   "x                                                                                         yyyy                   x",
   "x    o          yyyyy        yyyyy = = = = yyyyy       yyyyyyyyyyy     yyyyyyyyyyyy                       o o o  x",
   "x                                                                                                                x",
   "x                    | |  | |       | | |        | | |              |                                     o o o  x",
   "xxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x         x",
   "x         xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  o o o  x",
   "x                 o o                                                                        o                   x",
   "x o o o o                                         o o o o o o o         o o o o o o o                     o o o  x",
   "x                      o o                                                                   o                   x",
   "x o o o o                      o o                                                                               x",
   "x                                                        d                      d            yyyyy               x",
   "x o o o o   yyyyy  |                                                                                             x",
   "x                  | yy                                                                           |  |           x",
   "x                  |    |   yy                    o o o o o o o         o o o o o o o             |  |           x",
   "x                  |    |       |                                                                 |  |           x",
   "x                  |    |       |     yy          yyyyyyyyyyyyy=|=|=|=|=yyyyyyyyyyyyy             |  |           x",
   "x    g    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxx",
   "x         xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "x         x                                                                                                      x",
   "x         x                                                                                                      x",
   "x         x                                                                                                      x",
   "x         x                                                                                                      x",
   "x         x                                                                                                      x",
   "x         x                                                                                                      x",
   "x         x                                                                                                      x",
   "x         x                                                                                                      x",
   "x         x                                                                                                      x",
   "x         x                                                                                                      x",
   "x         x                                                                                                      x",
   "x         x                                                                                                      x",
   "x         x                                                                                                      x",
   "x         x                                                                                                      x",
   "x         x                                                                                                      x",
   "x         x                                                                                                      x",
   "x         x                                                                                                      x",
   "x         x                                                                                                      x",
   "x         x                                                                                                      x",
   "x         x                                                                                                      x",
   "x         x                                                                                                      x",
   "x         x                                                                                                      x",
   "x         x                                                                                                      x",
   "x         x                                                                                                      x",
   "x         x                                                                                                      x",
   "x         x                                                                                                      x"],
   
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                        o                                                                     ",
   "                                                                                                              ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                       xxx                                                                    ",
   "                                       x x                 !!!        !!!  xxx                                ",
   "                                       x x                 !x!        !x!                                     ",
   "                                     xxx xxx                x          x                                      ",
   "                                      x   x                 x   oooo   x       xxx                            ",
   "                                      x   x                 x          x      x!!!x                           ",
   "                                      x   x                 xxxxxxxxxxxx       xxx                            ",
   "                                     xx   xx      x   x      x                                                ",
   "                                      x   xxxxxxxxx   xxxxxxxx              x x                               ",
   "                                      x   x           x                    x!!!x                              ",
   "                                      x   x           x                     xxx                               ",
   "                                     xx   xx          x                                                       ",
   "                                      x   x= = = =    x            xxx                                        ",
   "                                      x   x           x           x!!!x                                       ",
   "                                      x   x    = = = =x     o      xxx       xxx                              ",
   "                                     xx   xx          x                     x!!!x                             ",
   "                              o   o   x   x           x     x                xxv        xxx                   ",
   "                                      x   x           x              x                 x!!!x                  ",
   "                             xxx xxx xxx xxx     o o  x!!!!!!!!!!!!!!x                   vx                   ",
   "                             x xxx x x xxx x          x!!!!!!!!!!!!!!x                                        ",
   "                             x             x   xxxxxxxxxxxxxxxxxxxxxxx                                        ",
   "                             xx           xx                                         xxx                      ",
   "  xxx                         x     x     x                                         x!!!x                xxx  ",
   "  x x                         x    xxx    x                                          xxx                 x x  ",
   "  x                           x    xxx    xxxxxxx                        xxxxx                             x  ",
   "  x                           x           x                              x   x                             x  ",
   "  x                           xx          x                              x x x                             x  ",
   "  x                                       x       |xxxx|    |xxxx|     xxx xxx                             x  ",
   "  x                xxx             o o    x                              x         xxx                     x  ",
   "  x               xxxxx       xx          x                             xxx       x!!!x          x         x  ",
   "  x               oxxxo       x    xxx    x                             x x        xxx          xxx        x  ",
   "  x                xxx        xxxxxxxxxxxxx  x oo x    x oo x    x oo  xx xx                    xxx        x  ",
   "  x      @     g    x         x           x!!x    x!!!!x    x!!!!x    xx   xx                    x         x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                                                  xxx x       ",
   "                                                                                                      x       ",
   "                                                                                                  xxxxx       ",
   "                                                                                                  x           ",
   "                                                                                                  x xxx       ",
   "                          o                                                                       x x x       ",
   "                                                                                             o o oxxx x       ",
   "                   xxx                                                                                x       ",
   "       !  o  !                                                xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx       ",
   "       x     x                                                x   x x   x x   x x   x x   x x   x x           ",
   "       x= o  x            x                                   xxx x xxx x xxx x xxx x xxx x xxx x xxxxx       ",
   "       x     x                                                  x x   x x   x x   x x   x x   x x     x       ",
   "       !  o  !            o                                  xxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxxxx       ",
   "                                                                                                              ",
   "          o              xxx                              xx                                                  ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                      xx                                                      ",
   "                   xxx         xxx                                                                            ",
   "                                                                                                              ",
   "                          o                                                     x      x                      ",
   "                                                          xx     xx                                           ",
   "             xxx         xxx         xxx                                 x                  x                 ",
   "                                                                                                              ",
   "                                                                 ||                                           ",
   "  xxxxxxxxxxx                                                                                                 ",
   "  x         x o xxxxxxxxx o xxxxxxxxx o xx                                                x                   ",
   "  x         x   x       x   x       x   x                 ||                  x     x                         ",
   "  x  @      xxxxx   o   xxxxx   o   xxxxx                                                                     ",
   "  xxxxxxx                                     xxxxx       xx     xx     xxx                                   ",
   "        x=         g        =                =x   x                     xxx                                   ",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
